# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Palash's Research Blog
email: tanejapalash@gmail.com
description: >
  My CS Research Blog.
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://palashtanejapro.github.io/" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Palash Taneja'
bio: >
  I am a high school senior who likes to tinker with computers and AI.
author_image: "/assets/images/author.jpg"
twitter_username:
github_username:  PalashTanejaPro

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true
  syntax_highlighter: rouge
plugins:
  - jekyll-paginate
  - jekyll-admin
